apiVersion: v2
name: groupsync
description: Usersync (group first search) replacement for Ranger
type: application
version: 1.0.0
appVersion: 1.0

home: https://github.com/thorbjornsen/groupsync
sources:
  - https://github.com/thorbjornsen/groupsync